language: java

sudo: true

addons:
  ulimit:
    nofile: 1048576

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "uqpMB9LWKmDDwOTZkGhaf7ROUaRPNYRSvHQewqBZKzCw/jox3vwoamsy4aNA3SD0cWgh64Ojk5lc4WV40pOQjL/5fRXen4/mqIr6uHxz5rJtij+8Bx9eYCVskY90b0DWHnT8+Vukm283p3ucP4B0tFSALKFiMFWOrG/kbEt3WBgMrWhBAFOcSvhAmtu+b4IuDaIF0n2gwh1TBL+s+UauZQ/nSzFLBLyjb2v68GIEZmsRUyw2aFEObutppj7STtnKr1Nu2G2/Pz53CtusRB947PWFH5j/WUz+OETuJ3o7Fq/HV1B7g4E3dxsflzLmXhwynAHLZUdbHFvMfQJ1kHKPOQwRsJA5jjJcuxDzNQ40PhsISePCMh/txyZuyUh7hLxH4yv2MZ6IlT/BSkhGlmFYOjmOuBfRTyKiqgLn7lXk8HqsJy4/FjoAh/Pjj979IC4MXWi40RXas0fKTcDVzk77qwuydC5V1VXDKuFF5fiPkfhcpaBQ0YDcUCSsbWonsB9G56v25FrBI1TE1JvKwsTkZZ3B8GuW6E1EvbxDduPDp/QZLeG3MTsjHdEyZUM7tz1U8ouGckibZ8cQdBml5ONgeUMPyp7J49AAZ7gO36p/ManDScAVLWeMAfXTKktBGO4otX2LygDiYUkH9a5eeJFWpRAkTc87jhn0CKgTBNigEw0="
  - secure: "behFDyjsAiKxoGoqroAXEfzQx6TdydnwEypEkUJ0lDjTgn2rq7BbAj6gW/nX0W4mfYGaalf/9KEc24qFy/7fly1RMuno6n+KN8eT0dBd0ZyS1rnDqOetuSoukVwEI/r8Yx4PWmNcHi+004GmKpZQILHtNs07rcSFzdiGlj+8YvFFMiIpubdjJq0+ikm+a7QzysMLC5OqSywda1HpxrYF0Nk3w8PSr/tLIkMMsUbr0CrZwaOpbqP8p3pvArTOZ0xNagtUUMq+efJkvTOXTYwfxGTcy+KsBFd6xPdCtwX5ru4NJFixnJhW4nKRf61jqzA41hsjgxcCx3IOpInSQAvmSfCi5dtsn8aYZ2oWPYVME4vhmHJbsYgohuQr5ax6X32ZOYNfBMmJP+AzF1rCgZpnZFOU856g8RziVKb5CeA91OqclAgmINgQGMGBVKIbhGEBkMvD8cGudGTsSthtBDpDJ0dm/j/U3OPoexrPAr+hb7sCZCQL6e5n7um/Um82eRg5LdR2+ZKdQ6CQcCWGVWJ5i5KqjyRfMW6lEfGtJPmPuds7oPgzGppyYh8UERh9OxU01tbvdjevLgheOH/wD8YF+HLEs7Yw7Fisu0m1L23SLYiVlmXOklvEP36BRuUi0RUykhf2/EdQjFRQR934DHKXR1r2cXYE2gn5C/Bx4/JB3ro="
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

jobs:
  include:

  - stage: "Tests"
    script: "./gradlew test"

  - stage: "System tests"
    env:
    - SUITE=api.storage
    - TEST=create_events
    script: "./gradlew robotest"

  - stage: "Deploy to DockerHub"
    script:
    - ./gradlew clean jar
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-pravega
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - docker build --build-arg MONGOOSE_VERSION=4.1.0 -f docker/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: "Deploy to GitHub releases"
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: sCzZ0wCOqzln2oQXkDSPr4Jv77QfktDStWD90y9VSS1lDn1CIRuH8OfUSnfeOmXtuNrMs+ngZw3e7y8QCCYpykancVKOpszgG1pYxcqEdFT9Dj8jzJAJXJZGHrT4E9lHFl3seNH0cFC5BCi2EyHP0Vb1MVBJKwSS0jW8oD9KLdcFaBM45RfTWMt22qHFEI+Bl6ButvRaGmCXgHqQ9fqu2yRaELl+pLT+D44ZS9uhHzoc0htbjnVyQWcCzzLxcAlP6r4YFlTqxznfALf0TRBkgvqqWZ2SnS3u8sd/TQMZAuKwIUFvhHLbiBkfrKH4Ers/gPzoJR8pi1/9CE9gAwHxaGPn2bcxYV/tKnD3B3BweMzairpoHd6um0Uas7EF5E7gj01DsvdgiMfA9PlDeDylzce8rJh5ZNVHGxI6INDDdmDUzo76s9W0d8bYJ5+rz2IfU5rGMaPckaq/b3tBN4yfdHxBAUE1R+OSd2TQ6YP6JP04McpTQb+D6Yo/ealyyt3Jh8Pz8pFq93FN0awUlE6fhIDvTqweBJh4quvGtydzbNukszgro2KMhiqaDuV4pXuIfNwy6KaNZDPui9zgRjDbTWFUlKQq2r0/Gk6tLu2ezPtsdS/KXMJlFkg8TCNN5PlTAlSAu9m8uXzm8/SRfMJvtLQB8pwz/oSjY0UNXHII9KQ=
        file: "./build/libs/mongoose-storage-driver-pravega.jar"
      on:
        tags: true
