language: java

sudo: true

addons:
  ulimit:
    nofile: 1048576

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Kj3SrVKLnacdCc6Rfi7Ms0Ql46ibf0A37wofQw+YJNGbdqT5G1WFSKJab1RmoUokiqfxxQGxTbGgICY41FOq0sI2yH95R5O7ViXVsLWqELu0RX/l12xe7w/wT+AEeCYqFrYMwipgY5F/paaYL7BE6lDjvhbtet4sr34WI1gwNAXdfVj6/jmzZOc2KOH4JMgvwQsnALAq5mKsUszpQB6dstufn0FKS6lKz6KP7ZEIPzOkR85ayI1VVNfb9md8v/PPryBjvlJ17SNgVhjeNs+IXXhyANL9OPWlM5djdvvwjWypILgCGb6+sUiQV1cbzQrrmAVjE5U2x5UEm1Pz1moTV3KG7pcxgBkY9+ZoMqJSDKYVILUd8vdIubM1hQjIwxBCcS0XHjEeRMa6Vaxx1FkdpKTgTpDxxYEBVxfLsHaYsT0V9d7gO5Vl4PUufArWkjG23s6LyXtwYdZYI3ltVgSnHYsjRaVwmm2U7Z2T0bvoSLezEirrGoJMA0OjMLGsVCuwTgsO/Sl4hxwjzl/F0pi29+YLMXclnaoXzBKRyXwBXMsmdAE1jQONY3fyuJTDudCoCTSxJuXImNOTlV/WLMzHo/QVGsG3rgIsiYYbjn8gha9delBccUGzzlvuOvOxdd1aoF8ATJRgQV4NKXY+H/4F9FuEq9L/4JTarbhGT9BfVTM=
  - secure: lJS63g+F1vpLeL9AKu9HUh/MvCVnsTQ8p/KTUhS3W1odLadYKY3/1WsicQpClDqzdm9vgOYbUjtTXPxfoQR8p+WhmOzyXK8Ypod3qz89dGxNvCHvfMdgPJ3+6BhZpOH2B26AqWOmRtfdEkxW7UeqeINJ2KppRlL2zdPS2kc1q4qwnqLntuGHheQDKhyyStUDaVnVNbIe+tLUjpxcQjd5y+6rbr3Tw6RczTjiF6w9M/L1ROWFBywalJGcUSsLtZA1tma159R1+83KN9XasJGATlAykg0ZKCdFeSaufwfbcmr5A9Qt8a4r1Y0v+CpRIQ71B6TO1tjwyzw4ksIcSOi5tHB7DdjRRFYX9xCpYHfN2zPbcttI7PRkEwPcLTDcHb7Gsf6x7/k4hC0FFLzQl0UD6NiTJxlZwNz3goOVBFYxNwbJxrjAzcKajpM7jGqiIzOEXBDHj8dmCZirxf3xGng00WVFCNxQDP+CvC9ndIhutvVT230t63QztDgjtdJbMGAS/mULwYe72XV96DCtr0mXnMK403br9tkOP9Hj8UI0EHMU/kJT3rFxbrXSCwQi/eycXVMAD7nthyTSBRttY8i54GLnR68Oz0Nm+5popUQ73JTGXi42E54xG5N9xqiBlKg5JloJ4VdjtZxYitYurmHLy2drHg+rs88DsTTLbI+vUlo=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

jobs:
  include:

  - stage: "Tests"
    script: "./gradlew test"

  - stage: "System tests"
    env:
    - SUITE=api.storage
    - TEST=create_events
    script: "./gradlew robotest"

  - env:
    - SUITE=api.storage
    - TEST=create_stream
    script: "./gradlew robotest"

  - stage: "Deploy to DockerHub"
    script:
    - ./gradlew clean jar
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-pravega
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - docker build --build-arg MONGOOSE_VERSION=${MONGOOSE_VERSION} -f docker/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: "Deploy to GitHub releases"
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: sCzZ0wCOqzln2oQXkDSPr4Jv77QfktDStWD90y9VSS1lDn1CIRuH8OfUSnfeOmXtuNrMs+ngZw3e7y8QCCYpykancVKOpszgG1pYxcqEdFT9Dj8jzJAJXJZGHrT4E9lHFl3seNH0cFC5BCi2EyHP0Vb1MVBJKwSS0jW8oD9KLdcFaBM45RfTWMt22qHFEI+Bl6ButvRaGmCXgHqQ9fqu2yRaELl+pLT+D44ZS9uhHzoc0htbjnVyQWcCzzLxcAlP6r4YFlTqxznfALf0TRBkgvqqWZ2SnS3u8sd/TQMZAuKwIUFvhHLbiBkfrKH4Ers/gPzoJR8pi1/9CE9gAwHxaGPn2bcxYV/tKnD3B3BweMzairpoHd6um0Uas7EF5E7gj01DsvdgiMfA9PlDeDylzce8rJh5ZNVHGxI6INDDdmDUzo76s9W0d8bYJ5+rz2IfU5rGMaPckaq/b3tBN4yfdHxBAUE1R+OSd2TQ6YP6JP04McpTQb+D6Yo/ealyyt3Jh8Pz8pFq93FN0awUlE6fhIDvTqweBJh4quvGtydzbNukszgro2KMhiqaDuV4pXuIfNwy6KaNZDPui9zgRjDbTWFUlKQq2r0/Gk6tLu2ezPtsdS/KXMJlFkg8TCNN5PlTAlSAu9m8uXzm8/SRfMJvtLQB8pwz/oSjY0UNXHII9KQ=
        file: "./build/libs/mongoose-storage-driver-pravega.jar"
      on:
        tags: true
