language: java

sudo: true

addons:
  ulimit:
    nofile: 1048576

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "EHtI+C9eLBt4DwqhCZYM2K9AU4XcJQmQ76mEblz3W6LdczI0h6G4MKRCRou3IZGK5T2wQ3fdx8Y8W9QaLMGOZ1nISVdbrRytNI7AKXxOCu2aMYrCycEyAcnBUa9l9rhfDTCTJobdhTzxkFY96+4v4AwW67Ow9D3aCLWQ06TYLJRlk9shcnESXtqhC9NTf9CzDZN9gsf2Lclp/g0XsOR0fe4Akhvb3yjjx/p+Tn6Z4bFjGjKeeXksCFBlDfom+cD4qgop5ked89kewfYVw/djm+eWC7Lfd5BscWIE39GPyc+enhBEX1gE0OuVqWWGdTBYf9hJHvyTMs244N3whAGxvJMzj6862oyfvM3mc+ztyXNQhvxJjdyoIbiHq18oD4yY0MB177H8A2oglEwmE+4XRtNwnaHXW890ZJDmHJjiuIEh1jORZLFw1YRJzEBA3ppzSKJp2J1UTj5eo5TKdEJ3/NN+L2YlsKj57jAYem8MMy5pm544SYH5NdJD8YwF6Z3AoPn8iOEcl/bghN4xpQBV3x7nK2zcpJy6HGzLQkIIXWjw0tA40n6M5kmefzxPi7hrAzJ+sa1bZwQxBr9yFx7uKQpYdSiToGI5j/sGSNg1UOQ+PgDRV3KOlzbZ6MQG1frr5Ho7WK4+0cb5t0UdBP5zE+iC8CSLeZKTj0bV+YNkWqM="
  - secure: "LaZGndnl0g8ViLySchcTNoJl+/1pUBV2IFqbzbnw7DRTnBAUeHSQFpTNYTybJ0/6u4AHEtSeVuV9c2AptcE8kU4epFC+PFCwNRt3z2/5csNdWtp/8lzAORWxfa4TWqVyE6zsCy3m2OtV3ihRtsSAt01JDVQ0EgJyWlBCuBmGDjwHzZULtm++UQMRRaPZ5EFfk/IUQMt+aJ/AAk9IS3+CHAP+POPOYCyIQ2fjd1GDAytF6hD4snG5QKFRIc5M2vjDkdb6nEADw9m2PHnsOy0kYURddTsaPR/HCWkJ4BEKKoTEHImnnwu939Nbz54ri2kXFryTiVA4tSZtJW1cyG/2+4CbnF7mgATyh+Pr5ncxYBYk4FMWlubUDNUD0FkMgFl8LFknsqHGWVUGCd1zNTsZtYcRP13p5XhTVO1DdIIcBiZ+IDyKT/r1x1TneQme1r+2Qd4Q5QINahJdT0tlDeFBxztj5WoXSXnX3vjfJZowJ5RlbJ9fl8xImy1YcQtTmvQ4hvz7o6FtVivMh+Li7Vnb4NGDifJ7nLqARNtwzhpp5KRGc4lQY52nb2B/EkR+zPHQI2M5C1wPdfKByn/ljDLXmvysJcSFlCy6th20dTxgVkGFyGLJuZXLEiDh3sS9ueR6ma1oKHLjW/KtaMeueiLRv4dmadyr6rEQn1+kZNghyI0="
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

jobs:
  include:

  - stage: "Integration Tests"
    script: "./gradlew test --tests com.emc.mongoose.storage.driver.pravega.integration.*"

  - stage: "System Tests"
    script:
    - "./gradlew clean jar"
    - "./gradlew test --tests com.emc.mongoose.storage.driver.pravega.system.*"

  - stage: "Deploy to DockerHub"
    script:
    - ./gradlew clean jar
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=emcmongoose/mongoose-storage-driver-pravega
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - docker build --build-arg MONGOOSE_VERSION=4.0.1 -f docker/Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

  - stage: "Deploy to GitHub releases"
    deploy:
      skip_cleanup: true
      provider: releases
      api_key:
        secure: LB0I2j3QWoR65Ty15ib8XV5ozIot72pD+6Mx1rcFht2VRajJPwqzOioH//pXHGKXgXNSaefqYqk19IrOFqrG3gykXsJO3AInVjtnt+g9vuPhjA+bXQxbfp8sTc99u6X7NalZB33SZy+O9N3S2tQ0pRtrsNfXKOrBPsro6LGDcZOYGHL2c2KMkFUF3LjPi1wSvea03DqIBCdvUhmD86krKJsNpK5lklz5HCADLfzp5VAERp1gAEYDvTXkn7wJiZhefbROPV0IoIBXjdKMTth3dEMsVObtD4eMXC3uiC90Jl+z/TzMxZ7H1vIobZtuNn6dZB32kMJRwLDK2DZ8kZiBkA7qXXHhRN2R/r84LUiGdp27QkV/ECiAMJjAae0zLaAp2rW1PA4OTFrVLuDcRBZIugLmAavZDD+k1rrF5ueFhSyw5w7mtFRLB2RMojwQ6U3i7Qf1NL37EHCTgGR5R9hzot+WQhNBqwrOUnkIlYDqNv20dfLEQyTVyustTeh7hvSrp2JDUIimAgojXW4X36R1zVtVH4fhKbay6dLncS9N+3bB1EpES+a0d4LTCYbuJwkg6VQYi9kfLBHMSLFQgMqKAIJrq9nkYQTmW5b423nyN7H85g5IQ8YGVeK6yHkNWXUMG6v9233aLG1BeB04X5ftzWo/7G3ra9ACvJ4Bvrg2Zo8=
      file: "./build/libs/mongoose-storage-driver-pravega.jar"
      on:
        tags: true

